# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
pool: 
  name: 'SelfHosted'
  vmImage: 'ZaitaOpenSuSe'

steps:
- script: |
    cd BuildSystem
    ./doBuild.sh thirdparty
  displayName: 'Build third-party libraries'

- script: |
    cd BuildSystem
    ./doBuild.sh debug
  displayName: 'Build "Debug" standalone binary'

- script: |
    cd BuildSystem
    ./doBuild.sh test
  displayName: 'Build "Unit Test" standalone binary'

- script: |
    cd BuildSystem/bin/linux_gcc/test/
    ./casal2
  displayName: 'Run Unit Tests standalone binary'

