# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo apt-get update
    sudo apt-get -y install gfortran-7
  displayName: 'Installing gfortran-7' 

- script: |
    sudo update-alternatives --remove-all gcc
    sudo update-alternatives --remove-all g++
    sudo update-alternatives --remove-all gfortran
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10
    sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 10
  displayName: 'Changing gcc, g++ and gfotran aliases' 

- script: |
    sudo apt -y install python3 python3-pip
    sudo pip3 install pytz
  displayName: 'Installing Python3 build environment'

- script: |
    cd BuildSystem
    ./doBuild.sh thirdparty
  displayName: 'Build third-party libraries'

- script: |
    cd BuildSystem
    ./doBuild.sh debug
  displayName: 'Build "Debug" standalone binary'

- script: |
    cd BuildSystem
    ./doBuild.sh test
  displayName: 'Build "Unit Test" standalone binary'

- script: |
    cd BuildSystem/bin/linux_gcc/test/
    ./casal2
  displayName: 'Run Unit Tests standalone binary'

