# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
pool:
  vmImage: 'windows-latest'

jobs:
- job: "Compile_Casal2"
  timeoutInMinutes: 0
  steps:
  - script: |
      pip install pytz
      pip3 install python-dateutil
    displayName: 'Installing Python3 build environment'

  - script: |
      cd BuildSystem
      doBuild.bat thirdparty adolc
    displayName: 'Build third-party library - adolc'

  - script: |
      cd BuildSystem
      doBuild.bat thirdparty betadiff
    displayName: 'Build third-party library - betadiff'

  - script: |
      cd BuildSystem
      doBuild.bat thirdparty boost
    displayName: 'Build third-party libraries - boost'

  - script: |
      cd BuildSystem
      doBuild.bat thirdparty googletest_googlemock
    displayName: 'Build third-party libraries - google test and mock'

  - script: |
      cd BuildSystem
      doBuild.bat thirdparty parser
    displayName: 'Build third-party libraries - parser'

  - script: |
      cd BuildSystem
      doBuild.bat debug
    displayName: 'Build "Debug" standalone binary'

  - script: |
      cd BuildSystem
      doBuild.bat test
    displayName: 'Build "Unit Test" standalone binary'

  - script: |
      BuildSystem\\bin\\windows_gcc\\test\\casal2.exe
    displayName: 'Run "Unit Test" standalone binary'

  - script: |
      cd BuildSystem
      doBuild.bat modelrunner
    displayName: 'Build "Unit Test" standalone binary'
