# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY doBuild version. DO NOT EDIT THIS FILE
Version<-"21.09 (2021-09-16)"
VersionNumber<-"21.09"
SourceControlRevision<-"9ed0b106ea90190e6ad14fd35d6ca4791b54e4cf"
SourceControlDateDoc<-"2021-09-16"
SourceControlYearDoc<-"2021"
SourceControlMonthDoc<-"September"
SourceControlTimeDoc<-"04:26:00"
SourceControlVersion<-"2021-09-16 04:26:00 UTC (rev. 9ed0b106)"
