# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY doBuild version. DO NOT EDIT THIS FILE
Version<-"21.09 (2021-09-15)"
VersionNumber<-"21.09"
SourceControlRevision<-"80ef1f7f9458b973bceb9848d7a928334f5378d8"
SourceControlDateDoc<-"2021-09-15"
SourceControlYearDoc<-"2021"
SourceControlMonthDoc<-"September"
SourceControlTimeDoc<-"10:43:17"
SourceControlVersion<-"2021-09-15 10:43:17 UTC (rev. 80ef1f7f)"
