# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY doBuild version. DO NOT EDIT THIS FILE
Version<-"22.01 (2022-01-11)"
VersionNumber<-"22.01"
SourceControlRevision<-"b6e1800a94d6a76bf77301087d94ca06318dfc65"
SourceControlDateDoc<-"2022-01-11"
SourceControlYearDoc<-"2022"
SourceControlMonthDoc<-"January"
SourceControlTimeDoc<-"21:02:47"
SourceControlVersion<-"2022-01-11 21:02:47 UTC (rev. b6e1800a)"
