# $Id: csl.commands.R 2264 2008-09-10 04:53:12Z adunn $
`csl.commands` <-
list(command = c("comment", "comment", "comment", "size_based", 
"n_classes", "class_mins", "min_age", "max_age", "plus_group", 
"plus_group_size", "sex_partition", "mature_partition", "n_areas", 
"area_names", "n_stocks", "stock_names", "n_growthpaths", "n_tags", 
"tag_names", "exclusions_char1", "exclusions_val1", "exclusions_char2", 
"exclusions_val2", "initial", "current", "final", "y_enter", 
"randomisation_method", "first_random_year", "selectivity_names", 
"use_mean_YCS", "standardise_YCS", "n_equilibrium", "Rinitial_is_deviate", 
"n_quant", "tag_shedding_rate", "tag_loss_props", "size_at_age_type", 
"size_at_age_years", "size_at_age_dist", "size_at_age_miss", 
"size_at_age_step", "annual_growths", "annual_growth_years", 
"weightless_model", "log_B0_total", "log_R0_total", "log_Bmean_total", 
"log_Rmean_total", "B0_total", "R0_total", "Bmean_total", "Rmean_total", 
"B0_prop_stock1", "R0_prop_stock1", "Bmean_prop_stock1", "Rmean_prop_stock1", 
"estimator", "max_iters", "max_evals", "max_iters_intermediate", 
"max_evals_intermediate", "grad_tol", "trivariate_normal_test", 
"q_method", "user_parameterisation", "user_components", "print_sizebased_ogives_at", 
"n_projections", "catch_split", "annual_cycle", "recruitment", 
"spawning_grounds", "growth", "maturation", "maturity_props", 
"migration", "natural_mortality", "fishery", "disease_mortality", 
"selectivity", "initialization", "size_at_age", "size_weight", 
"tag", "tag_growth_loss", "profile", "MCMC", "estimate", "q", 
"q_type", "abundance", "relative_abundance", "numbers_at", "relative_numbers_at", 
"proportions_at", "catch_at", "proportions_mature", "proportions_migrating", 
"age_size", "age_at_maturation", "selectivity_at", "tag_release", 
"tag_recapture", "ogive_smoothing_penalty", "catch_limit_penalty", 
"vector_average_penalty", "vector_smoothing_penalty", "element_difference_penalty", 
"YCS_difference_penalty", "similar_qs_penalty", "ratio_qs_penalty", 
"ogive_comparison_penalty", "ogive_difference_penalty", "fish_tagged_penalty", 
"ageing_error", "print", "quantities", "abundance", "numbers_at", 
"proportions_at", "catch_at", "proportions_mature", "proportions_migrating", 
"age_size", "age_at_maturation", "selectivity_at", "B_pre", "per_recruit", 
"deterministic_MSY", "MCY_CAY", "B_post", "CSP"), type = c("argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "argument", "argument", "argument", 
"argument", "argument", "argument", "nolabel", "labelifrepeated", 
"labelifrepeated", "autonumber", "autonumber", "nolabel", "label", 
"labelifrepeated", "label", "nolabel", "label", "labelifrepeated", 
"labelifrepeated", "labelifrepeated", "label", "label", "autonumber", 
"nolabel", "autonumber", "label", "argument", "label", "label", 
"label", "label", "label", "label", "label", "label", "label", 
"label", "label", "label", "label", "autonumber", "autonumber", 
"autonumber", "autonumber", "autonumber", "autonumber", "autonumber", 
"autonumber", "autonumber", "autonumber", "autonumber", "nolabel", 
"nolabel", "nolabel", "label", "label", "label", "label", "label", 
"label", "label", "label", "label", "nolabel", "nolabel", "nolabel", 
"nolabel", "nolabel", "nolabel"))
