name: Casal2 Linux Build
on:
  push:
    branches:
      - master # age_length_redesign_202109
  pull_request:
    branches:
      - master ## this will run actions on current branch, to change to main, needed for testing. all branches '*'
      ## taken from https://keithweaverca.medium.com/only-run-github-actions-on-specific-branches-694782fcc07
## for a release idea linux is fairly easy
## for windows look at this example https://github.com/freenet/wininstaller-innosetup/actions/runs/768471071/workflow
jobs:
  Compile-Casal2-Linux:
  # should run on linux based operating system
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      CC: gcc-14
      CXX: g++-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install python dependencies
        run: pip install pytz python-dateutil --user --upgrade pip

      - name: Install gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 14
          platform: x86
      - name: Build third-party library - release
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty

      - name: Build third-party library - adolc
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty adolc

      - name: Build third-party library - betadiff
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty betadiff

      - name: Build third-party libraries - boost
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty boost

      - name: Build third-party libraries - google test and mock
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty googletest_googlemock

      - name: Build third-party libraries - parser
        run: |
          cd BuildSystem
          ./doBuild.sh thirdparty parser

      - name: Build release library
        run: |
          cd BuildSystem
          ./doBuild.sh library release

      - name: Build "Betadiff" library
        run: |
          cd BuildSystem
          ./doBuild.sh library betadiff

      - name: Build "ADOL-C" library
        run: |
          cd BuildSystem
          ./doBuild.sh library adolc

      - name: Build "Unit Test" library
        run: |
          cd BuildSystem
          ./doBuild.sh library test

      - name: Build Frontend
        run: |
          cd BuildSystem
          ./doBuild.sh frontend
        shell: bash

      - name: Build Linux Archive
        continue-on-error: true
        run: |
          cd BuildSystem
          ./doBuild.sh archive true
        shell: bash

      - name: Archive Linux build
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: Casal2-Linux-build
          path: BuildSystem/Casal2
          retention-days: 1
          overwrite: true

      - name: Run Linux model runner
        continue-on-error: true
        run: |
          cd BuildSystem
          ./doBuild.sh modelrunner
          
      - name: Run Unit Tests from frontend build
        run: |
          cd BuildSystem/Casal2
          ./casal2 --unittest
          
  