on:
  push:
    branches:
      - AgeSizeObservation_202206
  pull_request:
    branches:
      - AgeSizeObservation_202206 
      
name: Check R Base Library

jobs:
  Compile-Casal2-linux:
  # should run on linux based operating system
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-20.04
    timeout-minutes: 150
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install python dependencies
        run: pip install pytz python-dateutil --user --upgrade pip

      - name: Install gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x86
      - name: Archive modelrunner
        continue-on-error: true
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Casal2-linux-modelrunner
          path: TestModels/
          
  
  Base-R-Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: R-libraries/casal2
          extra-packages: |
            any::devtools
            any::bayesplot
            any::purrr
            any::DHARMa
            any::mvtnorm
          dependencies: '"hard"'
      - name: Install Casal2 base
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
        run: Rscript -e 'devtools::install_github("https://github.com/NIWAFisheriesModelling/CASAL2", subdir="R-libraries/casal2", ref = "HEAD")'

        ## we want to download the model runner artefacts and then Run an Rscript
## that will 
    